blank_issues_enabled: true
contact_links:
  - name: Prywatne zgłoszenie problemu bezpieczeństwa
    url: https://github.com/CzubekxD/Excellence-News/security/advisories/new
    about: Podatności zgłaszaj tutaj, a nie w publicznym zgłoszeniu.
