// Generates the report nameplates (site/brand/nameplates/*.svg and index.json): the subject word
// from site/site.ts (in the accent) and the Polish title, set solid in Noto Sans Black (SIL OFL 1.1)
// as SVG paths, so the nameplate is one static logotype on every system. All capitals share one scale,
// centred on one line (diacritics such as Ę and Ń included), and the spacing is set by ink, pair by pair.
//
// Usage: node scripts/nameplates.ts <NotoSans_900Black.ttf>
//   (fetch it with `npm pack @expo-google-fonts/noto-sans@0.4.2` and untar; it is not a dependency)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import opentype from "opentype.js";
import { SITE } from "@aihot/site";

const file = process.argv[2];
if (!file) throw new Error("usage: node scripts/nameplates.ts <NotoSans_900Black.ttf>");

/** Ink height of the tallest capital (with its diacritic), in the nameplate's units. */
const H = 220;
const MARGIN = 12;
/** Space between the inks of two letters of one word, and between two words. */
const LETTER_GAP = H * 0.06;
const WORD_GAP = H * 0.3;

const S = SITE.subject.toUpperCase();
const NAMEPLATES: Record<string, Array<{ text: string; accent: boolean }>> = {
  daily: [
    { text: S, accent: true },
    { text: "DZIENNIK", accent: false },
  ],
  weekly: [
    { text: S, accent: true },
    { text: "TYGODNIK", accent: false },
  ],
  monthly: [
    { text: S, accent: true },
    { text: "MIESIĘCZNIK", accent: false },
  ],
  archive: [
    { text: "ARCHIWUM", accent: true },
    { text: "WYDAŃ", accent: false },
  ],
};

const buf = readFileSync(file);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

// One scale for every letter, from their union ink at 1000 units, centred on the line.
const chars = [...new Set(Object.values(NAMEPLATES).flatMap((parts) => parts.flatMap((p) => [...p.text.replace(/\s/g, "")])))];
const boxes = new Map(chars.map((ch) => [ch, font.getPath(ch, 0, 0, 1000).getBoundingBox()]));
const top = Math.min(...chars.map((ch) => boxes.get(ch)!.y1));
const bottom = Math.max(...chars.map((ch) => boxes.get(ch)!.y2));
const size = (1000 * H) / (bottom - top);
const baseline = -((top + bottom) / 2) * (size / 1000);
const scale = size / 1000;

const out: Record<string, { viewBox: string; accent: string; ink: string }> = {};
for (const [name, parts] of Object.entries(NAMEPLATES)) {
  const accent: string[] = [];
  const ink: string[] = [];
  let x = MARGIN;
  let first = true;
  for (const part of parts) {
    for (const word of part.text.split(/\s+/).filter(Boolean)) {
      if (!first) x += WORD_GAP;
      for (const [i, ch] of [...word].entries()) {
        const box = boxes.get(ch)!;
        if (i > 0) x += LETTER_GAP;
        const origin = x - box.x1 * scale;
        (part.accent ? accent : ink).push(font.getPath(ch, origin, baseline, size).toPathData(1));
        x = origin + box.x2 * scale;
      }
      first = false;
    }
  }
  const half = H / 2 + MARGIN;
  out[name] = { viewBox: `0 ${(-half).toFixed(1)} ${(x + MARGIN).toFixed(1)} ${(2 * half).toFixed(1)}`, accent: accent.join(" "), ink: ink.join(" ") };
}

const target = "site/brand/nameplates";
mkdirSync(target, { recursive: true });
for (const [name, n] of Object.entries(out)) {
  writeFileSync(`${target}/${name}.svg`, `<!-- Generated by scripts/nameplates.ts. Noto Sans Black (SIL OFL 1.1). -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="${n.viewBox}"><path id="accent" d="${n.accent}"/><path id="ink" d="${n.ink}"/></svg>\n`);
}
writeFileSync(`${target}/index.json`, `${JSON.stringify(Object.fromEntries(Object.entries(out).map(([k, v]) => [k, v.viewBox])), null, 2)}\n`);
console.log(target, Object.fromEntries(Object.entries(out).map(([k, v]) => [k, `${v.viewBox} · ${((v.accent.length + v.ink.length) / 1000).toFixed(1)} kB`])));
